apiVersion: apps/v1
kind: Deployment
metadata:
  name: parivesh-config
spec:
  selector:
    matchLabels:
      app: parivesh-config
  replicas: 2
  template:
    metadata:
      labels:
        app: parivesh-config
    spec:
      containers:
        - name: parivesh-config
          image: ${REPOSITORY_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: parivesh-config-svc
spec:
  selector:
    app: parivesh-config
  ports:
    - protocol: "TCP"
      port: 8888 # The port that the service is running on in the cluster
      targetPort: 8888 # The port exposed by the service
  type: ClusterIP # type of the service.
