apiVersion: apps/v1
kind: Deployment
metadata:
  name: parivesh-config
spec:
  selector:
    matchLabels:
      app: parivesh-config
  replicas: 2
  template:
    metadata:
      labels:
        app: parivesh-config
    spec:
      containers:
        - name: parivesh-config
          image: parivesh-config:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888